/*
 * SEVENSEGMENT_Private.h
 *
 *  Created on: Oct 30, 2023
 *      Author: mazak
 */

#ifndef HAL_SEVENSEGMENT_DRIVER_SEVENSEGMENT_PRIVATE_H_
#define HAL_SEVENSEGMENT_DRIVER_SEVENSEGMENT_PRIVATE_H_



#endif /* HAL_SEVENSEGMENT_DRIVER_SEVENSEGMENT_PRIVATE_H_ */
